#Makefile automatically created by mkmakefile (C)Christian Gosch

CXX		= mex 
CXXARGS		=  -DHAVE_MATLAB 

LD		= gcc
LDARGS		=  $(LDFLAGS) -lGo 

LIBS		=  

INCLUDE		= $(CPPFLAGS)

TARGET		= 

%.o: %.cxx
	$(CXX) $(CXXARGS) $(INCLUDE) -o $@ $<
%.o: %.cpp
	$(CXX) $(CXXARGS) $(INCLUDE) -o $@ $<
%.o: %.cc
	$(CXX) $(CXXARGS) $(INCLUDE) -o $@ $<
SOURCEDIRS = ./
SOURCES = videocapture.cpp
all: $(SOURCES)
	$(CXX) $(CXXARGS) $(LDARGS) $(LIBS) $(INCLUDE) $(SOURCES)
clean:
	rm -f *~ *.o
