# Include the progress variables for this target.
include progress.make

# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.4

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/christian/Software/bin/cmake

# The command to remove a file.
RM = /home/christian/Software/bin/cmake -E remove -f

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /home/christian/Software/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/christian/pgm/golib

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/christian/pgm/golib

# Default target executed when no arguments are given to make.
default_target: all

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/home/christian/Software/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/home/christian/Software/bin/cmake -P cmake_install.cmake

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/home/christian/Software/bin/cmake -P cmake_install.cmake

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/christian/Software/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

#=============================================================================
# Special targets provided by cmake.

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

.SUFFIXES: .hpux_make_needs_suffix_list

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/christian/pgm/golib/CMakeFiles $(CMAKE_ALL_PROGRESS)
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/christian/pgm/golib/CMakeFiles 0

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean

# The main clean target
clean/fast: clean

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1

#=============================================================================
# Target rules for targets named Gothread

# Build rule for target.
Gothread: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Gothread

# fast build rule for target.
Gothread/fast:
	$(MAKE) -f thread/CMakeFiles/Gothread.dir/build.make thread/CMakeFiles/Gothread.dir/build

#=============================================================================
# Target rules for targets named Godata

# Build rule for target.
Godata: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Godata

# fast build rule for target.
Godata/fast:
	$(MAKE) -f data/CMakeFiles/Godata.dir/build.make data/CMakeFiles/Godata.dir/build

#=============================================================================
# Target rules for targets named Gomath

# Build rule for target.
Gomath: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Gomath

# fast build rule for target.
Gomath/fast:
	$(MAKE) -f math/CMakeFiles/Gomath.dir/build.make math/CMakeFiles/Gomath.dir/build

#=============================================================================
# Target rules for targets named Gosignal

# Build rule for target.
Gosignal: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Gosignal

# fast build rule for target.
Gosignal/fast:
	$(MAKE) -f signal/CMakeFiles/Gosignal.dir/build.make signal/CMakeFiles/Gosignal.dir/build

# Help Target
help::
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... rebuild_cache"
	@echo "... Gothread"
	@echo "... Godata"
	@echo "... Gomath"
	@echo "... Gosignal"



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0

