# CMAKE generated Makefile, DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.0
# Generated from the following files:
# /home/christian/pgm/golib/CMakeCache.txt
# /home/christian/pgm/golib/CMakeCCompiler.cmake
# /home/christian/pgm/golib/CMakeCXXCompiler.cmake
# /home/christian/pgm/golib/CMakeLists.txt
# /home/christian/pgm/golib/CMakeSystem.cmake
# /home/christian/pgm/golib/include/goconfig.h.cmake.in
# /usr/share/CMake/Modules/CMakeDefaultMakeRuleVariables.cmake
# /usr/share/CMake/Modules/CMakeSystemSpecificInformation.cmake
# /usr/share/CMake/Modules/CheckFunctionExists.cmake
# /usr/share/CMake/Modules/CheckIncludeFile.cmake
# /usr/share/CMake/Modules/CheckLibraryExists.cmake
# /usr/share/CMake/Modules/CheckTypeSize.cmake
# /usr/share/CMake/Modules/Platform/Linux.cmake
# /usr/share/CMake/Modules/Platform/gcc.cmake


# disable some common implicit rules to speed things up
.SUFFIXES:
.SUFFIXES:.hpuxmakemusthaverule
CMAKE_MAKEFILE_SOURCES =  /home/christian/pgm/golib/CMakeCCompiler.cmake /home/christian/pgm/golib/CMakeCXXCompiler.cmake /home/christian/pgm/golib/CMakeLists.txt /home/christian/pgm/golib/CMakeSystem.cmake /home/christian/pgm/golib/include/goconfig.h.cmake.in /usr/share/CMake/Modules/CMakeDefaultMakeRuleVariables.cmake /usr/share/CMake/Modules/CMakeSystemSpecificInformation.cmake /usr/share/CMake/Modules/CheckFunctionExists.cmake /usr/share/CMake/Modules/CheckIncludeFile.cmake /usr/share/CMake/Modules/CheckLibraryExists.cmake /usr/share/CMake/Modules/CheckTypeSize.cmake /usr/share/CMake/Modules/Platform/Linux.cmake /usr/share/CMake/Modules/Platform/gcc.cmake /home/christian/pgm/golib/CMakeCache.txt


# the standard shell for make
SHELL = /bin/sh

CMAKE_COMMAND = /usr/bin/cmake
RM = /usr/bin/cmake -E remove -f
CMAKE_EDIT_COMMAND = /usr/bin/ccmake
CMAKE_CURRENT_SOURCE = /home/christian/pgm/golib
CMAKE_CURRENT_BINARY = /home/christian/pgm/golib
CMAKE_SOURCE_DIR = /home/christian/pgm/golib
CMAKE_BINARY_DIR = /home/christian/pgm/golib
INCLUDE_FLAGS = -I/home/christian/Software/include -I/home/christian/pgm/golib/include  

#---------------------------------------------------------
# Default target executed when no arguments are given to make, first make sure cmake.depends exists, cmake.check_depends is up-to-date, check the sources, then build the all target
#

default_target: /home/christian/pgm/golib/cmake.check_cache
	$(MAKE) $(MAKESILENT) cmake.depends
	$(MAKE) $(MAKESILENT) cmake.check_depends
	$(MAKE) $(MAKESILENT) -f cmake.check_depends
	$(MAKE) $(MAKESILENT) all

# Suppresses display of executed commands
$(VERBOSE).SILENT:

help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install"
	@echo "... rebuild_cache"
	@echo "... libGo.so"


TARGETS =  \
libGo.so

Go_SRC_OBJS = \
src/data/goarrayi.o\
src/data/golisti.o\
src/data/goheapi.o\
src/data/gotreei.o\
src/data/goqueuei.o\
src/data/gostring.o\
src/math/go3vectori.o\
src/math/go44matrix.o\
src/math/go4vectori.o\
src/math/gomatrixi.o\
src/math/gocomplex.o\
src/math/goposition.o\
src/math/goquaternion.o\
src/math/golinearalgebra.o\
src/math/gopdf.o\
src/math/gogausspdf.o\
src/math/gopoint.o\
src/math/gradient.o\
src/math/gomath.o\
src/math/divnormalizedgrad2d.o\
src/misc/goconfigfile.o\
src/misc/goconfigfileaccess.o\
src/misc/godate.o\
src/misc/goerror.o\
src/misc/goexception.o\
src/misc/gofileio.o\
src/misc/goobjectbase.o\
src/misc/gostatusobject.o\
src/misc/gotransferfunction.o\
src/misc/goobjectmessage.o\
src/misc/goglobal.o\
src/misc/golog.o\
src/network/goconnection.o\
src/network/gonetobject.o\
src/network/gonetwork.o\
src/network/goserver.o\
src/nifty/gorandom.o\
src/signal/gosignal3dbase.o\
src/signal/gosubsignal3d.o\
src/signal/gosignal3d.o\
src/signal/gosignal2d.o\
src/signal/gofilter3d.o\
src/signal/godwt.o\
src/signal/gohaar3d.o\
src/signal/godwt3d.o\
src/signal/gofilter1d.o\
src/signal/gosignalhelper.o\
src/signal/gohistogram.o\
src/signal/gosignal3diterator.o\
src/signal/gosignal3dgenericiterator.o\
src/system/godirectory.o\
src/system/goprocess.o\
src/thread/gothread.o\
src/thread/goconsumer.o\
src/thread/goproducer.o\
src/thread/gosynchronized.o\
src/thread/gothreadobject.o\
src/types/gotype.o

Go_EXTERNAL_OBJS = 

Go_SRC_OBJS_QUOTED = \
"src/data/goarrayi.o" \
"src/data/golisti.o" \
"src/data/goheapi.o" \
"src/data/gotreei.o" \
"src/data/goqueuei.o" \
"src/data/gostring.o" \
"src/math/go3vectori.o" \
"src/math/go44matrix.o" \
"src/math/go4vectori.o" \
"src/math/gomatrixi.o" \
"src/math/gocomplex.o" \
"src/math/goposition.o" \
"src/math/goquaternion.o" \
"src/math/golinearalgebra.o" \
"src/math/gopdf.o" \
"src/math/gogausspdf.o" \
"src/math/gopoint.o" \
"src/math/gradient.o" \
"src/math/gomath.o" \
"src/math/divnormalizedgrad2d.o" \
"src/misc/goconfigfile.o" \
"src/misc/goconfigfileaccess.o" \
"src/misc/godate.o" \
"src/misc/goerror.o" \
"src/misc/goexception.o" \
"src/misc/gofileio.o" \
"src/misc/goobjectbase.o" \
"src/misc/gostatusobject.o" \
"src/misc/gotransferfunction.o" \
"src/misc/goobjectmessage.o" \
"src/misc/goglobal.o" \
"src/misc/golog.o" \
"src/network/goconnection.o" \
"src/network/gonetobject.o" \
"src/network/gonetwork.o" \
"src/network/goserver.o" \
"src/nifty/gorandom.o" \
"src/signal/gosignal3dbase.o" \
"src/signal/gosubsignal3d.o" \
"src/signal/gosignal3d.o" \
"src/signal/gosignal2d.o" \
"src/signal/gofilter3d.o" \
"src/signal/godwt.o" \
"src/signal/gohaar3d.o" \
"src/signal/godwt3d.o" \
"src/signal/gofilter1d.o" \
"src/signal/gosignalhelper.o" \
"src/signal/gohistogram.o" \
"src/signal/gosignal3diterator.o" \
"src/signal/gosignal3dgenericiterator.o" \
"src/system/godirectory.o" \
"src/system/goprocess.o" \
"src/thread/gothread.o" \
"src/thread/goconsumer.o" \
"src/thread/goproducer.o" \
"src/thread/gosynchronized.o" \
"src/thread/gothreadobject.o" \
"src/types/gotype.o" 

Go_EXTERNAL_OBJS_QUOTED = 

TARGET_EXTRAS = 

CLEAN_OBJECT_FILES = $(Go_SRC_OBJS) 

Go_DEPEND_LIBS = 

#---------------------------------------------------------
# shared library
#

libGo.so: $(Go_SRC_OBJS) $(Go_EXTERNAL_OBJS)  $(Go_DEPEND_LIBS)
	@echo "Building shared library libGo.so..."
	/usr/bin/cmake -E remove -f libGo.so
	c++ -fPIC -L/home/christian/pgm/lib  -shared -Wl,-soname,libGo.so -o libGo.so $(Go_SRC_OBJS) $(Go_EXTERNAL_OBJS)   -lIL -lILU -lnsl -lpthread  -lgcc

#---------------------------------------------------------
# shared library
#

Go: libGo.so

#---------------------------------------------------------
# default build rule
#

all: cmake.depends $(SUBDIR_PREORDER_BUILD) $(TARGETS) $(SUBDIR_BUILD)

#---------------------------------------------------------
# clean generated files
#

clean: $(SUBDIR_CLEAN)
	-@ $(RM) $(CLEAN_OBJECT_FILES)  $(TARGETS) $(TARGET_EXTRAS) $(GENERATED_QT_FILES) $(GENERATED_FLTK_FILES) $(ADDITIONAL_MAKE_CLEAN_FILES)

#---------------------------------------------------------
# dependencies.
#

cmake.depends: $(CMAKE_MAKEFILE_SOURCES)
	@echo "Building dependencies. cmake.depends..."
	$(CMAKE_COMMAND) -S$(CMAKE_CURRENT_SOURCE) -O$(CMAKE_CURRENT_BINARY) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)

#---------------------------------------------------------
# dependencies
#

cmake.check_depends: /home/christian/pgm/golib/src/data/goarrayi.cc
cmake.check_depends: /home/christian/pgm/golib/src/data/golisti.cc
cmake.check_depends: /home/christian/pgm/golib/src/data/goheapi.cc
cmake.check_depends: /home/christian/pgm/golib/src/data/gotreei.cc
cmake.check_depends: /home/christian/pgm/golib/src/data/goqueuei.cc
cmake.check_depends: /home/christian/pgm/golib/src/data/gostring.cc
cmake.check_depends: /home/christian/pgm/golib/src/math/go3vectori.cc
cmake.check_depends: /home/christian/pgm/golib/src/math/go44matrix.cc
cmake.check_depends: /home/christian/pgm/golib/src/math/go4vectori.cc
cmake.check_depends: /home/christian/pgm/golib/src/math/gomatrixi.cc
cmake.check_depends: /home/christian/pgm/golib/src/math/gocomplex.cc
cmake.check_depends: /home/christian/pgm/golib/src/math/goposition.cc
cmake.check_depends: /home/christian/pgm/golib/src/math/goquaternion.cc
cmake.check_depends: /home/christian/pgm/golib/src/math/golinearalgebra.cc
cmake.check_depends: /home/christian/pgm/golib/src/math/gopdf.cpp
cmake.check_depends: /home/christian/pgm/golib/src/math/gogausspdf.cpp
cmake.check_depends: /home/christian/pgm/golib/src/math/gopoint.cpp
cmake.check_depends: /home/christian/pgm/golib/src/math/gradient.cpp
cmake.check_depends: /home/christian/pgm/golib/src/math/gomath.cpp
cmake.check_depends: /home/christian/pgm/golib/src/math/divnormalizedgrad2d.cpp
cmake.check_depends: /home/christian/pgm/golib/src/misc/goconfigfile.cc
cmake.check_depends: /home/christian/pgm/golib/src/misc/goconfigfileaccess.cc
cmake.check_depends: /home/christian/pgm/golib/src/misc/godate.cc
cmake.check_depends: /home/christian/pgm/golib/src/misc/goerror.cc
cmake.check_depends: /home/christian/pgm/golib/src/misc/goexception.cc
cmake.check_depends: /home/christian/pgm/golib/src/misc/gofileio.cc
cmake.check_depends: /home/christian/pgm/golib/src/misc/goobjectbase.cc
cmake.check_depends: /home/christian/pgm/golib/src/misc/gostatusobject.cc
cmake.check_depends: /home/christian/pgm/golib/src/misc/gotransferfunction.cc
cmake.check_depends: /home/christian/pgm/golib/src/misc/goobjectmessage.cc
cmake.check_depends: /home/christian/pgm/golib/src/misc/goglobal.cpp
cmake.check_depends: /home/christian/pgm/golib/src/misc/golog.cpp
cmake.check_depends: /home/christian/pgm/golib/src/network/goconnection.cc
cmake.check_depends: /home/christian/pgm/golib/src/network/gonetobject.cc
cmake.check_depends: /home/christian/pgm/golib/src/network/gonetwork.cc
cmake.check_depends: /home/christian/pgm/golib/src/network/goserver.cc
cmake.check_depends: /home/christian/pgm/golib/src/nifty/gorandom.cc
cmake.check_depends: /home/christian/pgm/golib/src/signal/gosignal3dbase.cpp
cmake.check_depends: /home/christian/pgm/golib/src/signal/gosubsignal3d.cc
cmake.check_depends: /home/christian/pgm/golib/src/signal/gosignal3d.cc
cmake.check_depends: /home/christian/pgm/golib/src/signal/gosignal2d.cc
cmake.check_depends: /home/christian/pgm/golib/src/signal/gofilter3d.cpp
cmake.check_depends: /home/christian/pgm/golib/src/signal/godwt.cc
cmake.check_depends: /home/christian/pgm/golib/src/signal/gohaar3d.cpp
cmake.check_depends: /home/christian/pgm/golib/src/signal/godwt3d.cpp
cmake.check_depends: /home/christian/pgm/golib/src/signal/gofilter1d.cpp
cmake.check_depends: /home/christian/pgm/golib/src/signal/gosignalhelper.cpp
cmake.check_depends: /home/christian/pgm/golib/src/signal/gohistogram.cpp
cmake.check_depends: /home/christian/pgm/golib/src/signal/gosignal3diterator.cpp
cmake.check_depends: /home/christian/pgm/golib/src/signal/gosignal3dgenericiterator.cpp
cmake.check_depends: /home/christian/pgm/golib/src/system/godirectory.cc
cmake.check_depends: /home/christian/pgm/golib/src/system/goprocess.cc
cmake.check_depends: /home/christian/pgm/golib/src/thread/gothread.cc
cmake.check_depends: /home/christian/pgm/golib/src/thread/goconsumer.cc
cmake.check_depends: /home/christian/pgm/golib/src/thread/goproducer.cc
cmake.check_depends: /home/christian/pgm/golib/src/thread/gosynchronized.cc
cmake.check_depends: /home/christian/pgm/golib/src/thread/gothreadobject.cc
cmake.check_depends: /home/christian/pgm/golib/src/types/gotype.cpp
	@echo "Building dependencies cmake.check_depends..."
	$(CMAKE_COMMAND) -S$(CMAKE_CURRENT_SOURCE) -O$(CMAKE_CURRENT_BINARY) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)

#---------------------------------------------------------
# dependencies
#

depend: $(SUBDIR_DEPEND)
	@echo "Building dependencies depend..."
	$(CMAKE_COMMAND) -S$(CMAKE_CURRENT_SOURCE) -O$(CMAKE_CURRENT_BINARY) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)

#---------------------------------------------------------
# dependencies
#

dependlocal:
	@echo "Building dependencies dependlocal..."
	$(CMAKE_COMMAND) -S$(CMAKE_CURRENT_SOURCE) -O$(CMAKE_CURRENT_BINARY) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)

#---------------------------------------------------------
# CMakeCache.txt
#

rebuild_cache:
	@echo "Building CMakeCache.txt rebuild_cache..."
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)

#---------------------------------------------------------
# CMakeCache.txt because out-of-date:
#

/home/christian/pgm/golib/cmake.check_cache: $(CMAKE_MAKEFILE_SOURCES)
	@echo "Building CMakeCache.txt because out-of-date: /home/christian/pgm/golib/cmake.check_cache..."
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)

#---------------------------------------------------------
# edit CMakeCache.txt
#

edit_cache:
	@echo "Building edit CMakeCache.txt edit_cache..."
	$(CMAKE_EDIT_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)

#---------------------------------------------------------
# CMakeCache.txt
#

/home/christian/pgm/golib/CMakeCache.txt:
	@echo "Building CMakeCache.txt /home/christian/pgm/golib/CMakeCache.txt..."
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)

#---------------------------------------------------------
# Rule to keep make from removing Makefiles if control-C is hit during a run of cmake.
#

.PRECIOUS: Makefile cmake.depends

# Rules to build .o files from their sources:
#---------------------------------------------------------
# object file
#

src/data/goarrayi.o: /home/christian/pgm/golib/src/data/goarrayi.cc
	@echo "Building object file src/data/goarrayi.o..."
	c++ -o src/data/goarrayi.o -DGo_EXPORTS    -fPIC $(INCLUDE_FLAGS)  -c /home/christian/pgm/golib/src/data/goarrayi.cc

#---------------------------------------------------------
# object file
#

src/data/golisti.o: /home/christian/pgm/golib/src/data/golisti.cc
	@echo "Building object file src/data/golisti.o..."
	c++ -o src/data/golisti.o -DGo_EXPORTS    -fPIC $(INCLUDE_FLAGS)  -c /home/christian/pgm/golib/src/data/golisti.cc

#---------------------------------------------------------
# object file
#

src/data/goheapi.o: /home/christian/pgm/golib/src/data/goheapi.cc
	@echo "Building object file src/data/goheapi.o..."
	c++ -o src/data/goheapi.o -DGo_EXPORTS    -fPIC $(INCLUDE_FLAGS)  -c /home/christian/pgm/golib/src/data/goheapi.cc

#---------------------------------------------------------
# object file
#

src/data/gotreei.o: /home/christian/pgm/golib/src/data/gotreei.cc
	@echo "Building object file src/data/gotreei.o..."
	c++ -o src/data/gotreei.o -DGo_EXPORTS    -fPIC $(INCLUDE_FLAGS)  -c /home/christian/pgm/golib/src/data/gotreei.cc

#---------------------------------------------------------
# object file
#

src/data/goqueuei.o: /home/christian/pgm/golib/src/data/goqueuei.cc
	@echo "Building object file src/data/goqueuei.o..."
	c++ -o src/data/goqueuei.o -DGo_EXPORTS    -fPIC $(INCLUDE_FLAGS)  -c /home/christian/pgm/golib/src/data/goqueuei.cc

#---------------------------------------------------------
# object file
#

src/data/gostring.o: /home/christian/pgm/golib/src/data/gostring.cc
	@echo "Building object file src/data/gostring.o..."
	c++ -o src/data/gostring.o -DGo_EXPORTS    -fPIC $(INCLUDE_FLAGS)  -c /home/christian/pgm/golib/src/data/gostring.cc

#---------------------------------------------------------
# object file
#

src/math/go3vectori.o: /home/christian/pgm/golib/src/math/go3vectori.cc
	@echo "Building object file src/math/go3vectori.o..."
	c++ -o src/math/go3vectori.o -DGo_EXPORTS    -fPIC $(INCLUDE_FLAGS)  -c /home/christian/pgm/golib/src/math/go3vectori.cc

#---------------------------------------------------------
# object file
#

src/math/go44matrix.o: /home/christian/pgm/golib/src/math/go44matrix.cc
	@echo "Building object file src/math/go44matrix.o..."
	c++ -o src/math/go44matrix.o -DGo_EXPORTS    -fPIC $(INCLUDE_FLAGS)  -c /home/christian/pgm/golib/src/math/go44matrix.cc

#---------------------------------------------------------
# object file
#

src/math/go4vectori.o: /home/christian/pgm/golib/src/math/go4vectori.cc
	@echo "Building object file src/math/go4vectori.o..."
	c++ -o src/math/go4vectori.o -DGo_EXPORTS    -fPIC $(INCLUDE_FLAGS)  -c /home/christian/pgm/golib/src/math/go4vectori.cc

#---------------------------------------------------------
# object file
#

src/math/gomatrixi.o: /home/christian/pgm/golib/src/math/gomatrixi.cc
	@echo "Building object file src/math/gomatrixi.o..."
	c++ -o src/math/gomatrixi.o -DGo_EXPORTS    -fPIC $(INCLUDE_FLAGS)  -c /home/christian/pgm/golib/src/math/gomatrixi.cc

#---------------------------------------------------------
# object file
#

src/math/gocomplex.o: /home/christian/pgm/golib/src/math/gocomplex.cc
	@echo "Building object file src/math/gocomplex.o..."
	c++ -o src/math/gocomplex.o -DGo_EXPORTS    -fPIC $(INCLUDE_FLAGS)  -c /home/christian/pgm/golib/src/math/gocomplex.cc

#---------------------------------------------------------
# object file
#

src/math/goposition.o: /home/christian/pgm/golib/src/math/goposition.cc
	@echo "Building object file src/math/goposition.o..."
	c++ -o src/math/goposition.o -DGo_EXPORTS    -fPIC $(INCLUDE_FLAGS)  -c /home/christian/pgm/golib/src/math/goposition.cc

#---------------------------------------------------------
# object file
#

src/math/goquaternion.o: /home/christian/pgm/golib/src/math/goquaternion.cc
	@echo "Building object file src/math/goquaternion.o..."
	c++ -o src/math/goquaternion.o -DGo_EXPORTS    -fPIC $(INCLUDE_FLAGS)  -c /home/christian/pgm/golib/src/math/goquaternion.cc

#---------------------------------------------------------
# object file
#

src/math/golinearalgebra.o: /home/christian/pgm/golib/src/math/golinearalgebra.cc
	@echo "Building object file src/math/golinearalgebra.o..."
	c++ -o src/math/golinearalgebra.o -DGo_EXPORTS    -fPIC $(INCLUDE_FLAGS)  -c /home/christian/pgm/golib/src/math/golinearalgebra.cc

#---------------------------------------------------------
# object file
#

src/math/gopdf.o: /home/christian/pgm/golib/src/math/gopdf.cpp
	@echo "Building object file src/math/gopdf.o..."
	c++ -o src/math/gopdf.o -DGo_EXPORTS    -fPIC $(INCLUDE_FLAGS)  -c /home/christian/pgm/golib/src/math/gopdf.cpp

#---------------------------------------------------------
# object file
#

src/math/gogausspdf.o: /home/christian/pgm/golib/src/math/gogausspdf.cpp
	@echo "Building object file src/math/gogausspdf.o..."
	c++ -o src/math/gogausspdf.o -DGo_EXPORTS    -fPIC $(INCLUDE_FLAGS)  -c /home/christian/pgm/golib/src/math/gogausspdf.cpp

#---------------------------------------------------------
# object file
#

src/math/gopoint.o: /home/christian/pgm/golib/src/math/gopoint.cpp
	@echo "Building object file src/math/gopoint.o..."
	c++ -o src/math/gopoint.o -DGo_EXPORTS    -fPIC $(INCLUDE_FLAGS)  -c /home/christian/pgm/golib/src/math/gopoint.cpp

#---------------------------------------------------------
# object file
#

src/math/gradient.o: /home/christian/pgm/golib/src/math/gradient.cpp
	@echo "Building object file src/math/gradient.o..."
	c++ -o src/math/gradient.o -DGo_EXPORTS    -fPIC $(INCLUDE_FLAGS)  -c /home/christian/pgm/golib/src/math/gradient.cpp

#---------------------------------------------------------
# object file
#

src/math/gomath.o: /home/christian/pgm/golib/src/math/gomath.cpp
	@echo "Building object file src/math/gomath.o..."
	c++ -o src/math/gomath.o -DGo_EXPORTS    -fPIC $(INCLUDE_FLAGS)  -c /home/christian/pgm/golib/src/math/gomath.cpp

#---------------------------------------------------------
# object file
#

src/math/divnormalizedgrad2d.o: /home/christian/pgm/golib/src/math/divnormalizedgrad2d.cpp
	@echo "Building object file src/math/divnormalizedgrad2d.o..."
	c++ -o src/math/divnormalizedgrad2d.o -DGo_EXPORTS    -fPIC $(INCLUDE_FLAGS)  -c /home/christian/pgm/golib/src/math/divnormalizedgrad2d.cpp

#---------------------------------------------------------
# object file
#

src/misc/goconfigfile.o: /home/christian/pgm/golib/src/misc/goconfigfile.cc
	@echo "Building object file src/misc/goconfigfile.o..."
	c++ -o src/misc/goconfigfile.o -DGo_EXPORTS    -fPIC $(INCLUDE_FLAGS)  -c /home/christian/pgm/golib/src/misc/goconfigfile.cc

#---------------------------------------------------------
# object file
#

src/misc/goconfigfileaccess.o: /home/christian/pgm/golib/src/misc/goconfigfileaccess.cc
	@echo "Building object file src/misc/goconfigfileaccess.o..."
	c++ -o src/misc/goconfigfileaccess.o -DGo_EXPORTS    -fPIC $(INCLUDE_FLAGS)  -c /home/christian/pgm/golib/src/misc/goconfigfileaccess.cc

#---------------------------------------------------------
# object file
#

src/misc/godate.o: /home/christian/pgm/golib/src/misc/godate.cc
	@echo "Building object file src/misc/godate.o..."
	c++ -o src/misc/godate.o -DGo_EXPORTS    -fPIC $(INCLUDE_FLAGS)  -c /home/christian/pgm/golib/src/misc/godate.cc

#---------------------------------------------------------
# object file
#

src/misc/goerror.o: /home/christian/pgm/golib/src/misc/goerror.cc
	@echo "Building object file src/misc/goerror.o..."
	c++ -o src/misc/goerror.o -DGo_EXPORTS    -fPIC $(INCLUDE_FLAGS)  -c /home/christian/pgm/golib/src/misc/goerror.cc

#---------------------------------------------------------
# object file
#

src/misc/goexception.o: /home/christian/pgm/golib/src/misc/goexception.cc
	@echo "Building object file src/misc/goexception.o..."
	c++ -o src/misc/goexception.o -DGo_EXPORTS    -fPIC $(INCLUDE_FLAGS)  -c /home/christian/pgm/golib/src/misc/goexception.cc

#---------------------------------------------------------
# object file
#

src/misc/gofileio.o: /home/christian/pgm/golib/src/misc/gofileio.cc
	@echo "Building object file src/misc/gofileio.o..."
	c++ -o src/misc/gofileio.o -DGo_EXPORTS    -fPIC $(INCLUDE_FLAGS)  -c /home/christian/pgm/golib/src/misc/gofileio.cc

#---------------------------------------------------------
# object file
#

src/misc/goobjectbase.o: /home/christian/pgm/golib/src/misc/goobjectbase.cc
	@echo "Building object file src/misc/goobjectbase.o..."
	c++ -o src/misc/goobjectbase.o -DGo_EXPORTS    -fPIC $(INCLUDE_FLAGS)  -c /home/christian/pgm/golib/src/misc/goobjectbase.cc

#---------------------------------------------------------
# object file
#

src/misc/gostatusobject.o: /home/christian/pgm/golib/src/misc/gostatusobject.cc
	@echo "Building object file src/misc/gostatusobject.o..."
	c++ -o src/misc/gostatusobject.o -DGo_EXPORTS    -fPIC $(INCLUDE_FLAGS)  -c /home/christian/pgm/golib/src/misc/gostatusobject.cc

#---------------------------------------------------------
# object file
#

src/misc/gotransferfunction.o: /home/christian/pgm/golib/src/misc/gotransferfunction.cc
	@echo "Building object file src/misc/gotransferfunction.o..."
	c++ -o src/misc/gotransferfunction.o -DGo_EXPORTS    -fPIC $(INCLUDE_FLAGS)  -c /home/christian/pgm/golib/src/misc/gotransferfunction.cc

#---------------------------------------------------------
# object file
#

src/misc/goobjectmessage.o: /home/christian/pgm/golib/src/misc/goobjectmessage.cc
	@echo "Building object file src/misc/goobjectmessage.o..."
	c++ -o src/misc/goobjectmessage.o -DGo_EXPORTS    -fPIC $(INCLUDE_FLAGS)  -c /home/christian/pgm/golib/src/misc/goobjectmessage.cc

#---------------------------------------------------------
# object file
#

src/misc/goglobal.o: /home/christian/pgm/golib/src/misc/goglobal.cpp
	@echo "Building object file src/misc/goglobal.o..."
	c++ -o src/misc/goglobal.o -DGo_EXPORTS    -fPIC $(INCLUDE_FLAGS)  -c /home/christian/pgm/golib/src/misc/goglobal.cpp

#---------------------------------------------------------
# object file
#

src/misc/golog.o: /home/christian/pgm/golib/src/misc/golog.cpp
	@echo "Building object file src/misc/golog.o..."
	c++ -o src/misc/golog.o -DGo_EXPORTS    -fPIC $(INCLUDE_FLAGS)  -c /home/christian/pgm/golib/src/misc/golog.cpp

#---------------------------------------------------------
# object file
#

src/network/goconnection.o: /home/christian/pgm/golib/src/network/goconnection.cc
	@echo "Building object file src/network/goconnection.o..."
	c++ -o src/network/goconnection.o -DGo_EXPORTS    -fPIC $(INCLUDE_FLAGS)  -c /home/christian/pgm/golib/src/network/goconnection.cc

#---------------------------------------------------------
# object file
#

src/network/gonetobject.o: /home/christian/pgm/golib/src/network/gonetobject.cc
	@echo "Building object file src/network/gonetobject.o..."
	c++ -o src/network/gonetobject.o -DGo_EXPORTS    -fPIC $(INCLUDE_FLAGS)  -c /home/christian/pgm/golib/src/network/gonetobject.cc

#---------------------------------------------------------
# object file
#

src/network/gonetwork.o: /home/christian/pgm/golib/src/network/gonetwork.cc
	@echo "Building object file src/network/gonetwork.o..."
	c++ -o src/network/gonetwork.o -DGo_EXPORTS    -fPIC $(INCLUDE_FLAGS)  -c /home/christian/pgm/golib/src/network/gonetwork.cc

#---------------------------------------------------------
# object file
#

src/network/goserver.o: /home/christian/pgm/golib/src/network/goserver.cc
	@echo "Building object file src/network/goserver.o..."
	c++ -o src/network/goserver.o -DGo_EXPORTS    -fPIC $(INCLUDE_FLAGS)  -c /home/christian/pgm/golib/src/network/goserver.cc

#---------------------------------------------------------
# object file
#

src/nifty/gorandom.o: /home/christian/pgm/golib/src/nifty/gorandom.cc
	@echo "Building object file src/nifty/gorandom.o..."
	c++ -o src/nifty/gorandom.o -DGo_EXPORTS    -fPIC $(INCLUDE_FLAGS)  -c /home/christian/pgm/golib/src/nifty/gorandom.cc

#---------------------------------------------------------
# object file
#

src/signal/gosignal3dbase.o: /home/christian/pgm/golib/src/signal/gosignal3dbase.cpp
	@echo "Building object file src/signal/gosignal3dbase.o..."
	c++ -o src/signal/gosignal3dbase.o -DGo_EXPORTS    -fPIC $(INCLUDE_FLAGS)  -c /home/christian/pgm/golib/src/signal/gosignal3dbase.cpp

#---------------------------------------------------------
# object file
#

src/signal/gosubsignal3d.o: /home/christian/pgm/golib/src/signal/gosubsignal3d.cc
	@echo "Building object file src/signal/gosubsignal3d.o..."
	c++ -o src/signal/gosubsignal3d.o -DGo_EXPORTS    -fPIC $(INCLUDE_FLAGS)  -c /home/christian/pgm/golib/src/signal/gosubsignal3d.cc

#---------------------------------------------------------
# object file
#

src/signal/gosignal3d.o: /home/christian/pgm/golib/src/signal/gosignal3d.cc
	@echo "Building object file src/signal/gosignal3d.o..."
	c++ -o src/signal/gosignal3d.o -DGo_EXPORTS    -fPIC $(INCLUDE_FLAGS)  -c /home/christian/pgm/golib/src/signal/gosignal3d.cc

#---------------------------------------------------------
# object file
#

src/signal/gosignal2d.o: /home/christian/pgm/golib/src/signal/gosignal2d.cc
	@echo "Building object file src/signal/gosignal2d.o..."
	c++ -o src/signal/gosignal2d.o -DGo_EXPORTS    -fPIC $(INCLUDE_FLAGS)  -c /home/christian/pgm/golib/src/signal/gosignal2d.cc

#---------------------------------------------------------
# object file
#

src/signal/gofilter3d.o: /home/christian/pgm/golib/src/signal/gofilter3d.cpp
	@echo "Building object file src/signal/gofilter3d.o..."
	c++ -o src/signal/gofilter3d.o -DGo_EXPORTS    -fPIC $(INCLUDE_FLAGS)  -c /home/christian/pgm/golib/src/signal/gofilter3d.cpp

#---------------------------------------------------------
# object file
#

src/signal/godwt.o: /home/christian/pgm/golib/src/signal/godwt.cc
	@echo "Building object file src/signal/godwt.o..."
	c++ -o src/signal/godwt.o -DGo_EXPORTS    -fPIC $(INCLUDE_FLAGS)  -c /home/christian/pgm/golib/src/signal/godwt.cc

#---------------------------------------------------------
# object file
#

src/signal/gohaar3d.o: /home/christian/pgm/golib/src/signal/gohaar3d.cpp
	@echo "Building object file src/signal/gohaar3d.o..."
	c++ -o src/signal/gohaar3d.o -DGo_EXPORTS    -fPIC $(INCLUDE_FLAGS)  -c /home/christian/pgm/golib/src/signal/gohaar3d.cpp

#---------------------------------------------------------
# object file
#

src/signal/godwt3d.o: /home/christian/pgm/golib/src/signal/godwt3d.cpp
	@echo "Building object file src/signal/godwt3d.o..."
	c++ -o src/signal/godwt3d.o -DGo_EXPORTS    -fPIC $(INCLUDE_FLAGS)  -c /home/christian/pgm/golib/src/signal/godwt3d.cpp

#---------------------------------------------------------
# object file
#

src/signal/gofilter1d.o: /home/christian/pgm/golib/src/signal/gofilter1d.cpp
	@echo "Building object file src/signal/gofilter1d.o..."
	c++ -o src/signal/gofilter1d.o -DGo_EXPORTS    -fPIC $(INCLUDE_FLAGS)  -c /home/christian/pgm/golib/src/signal/gofilter1d.cpp

#---------------------------------------------------------
# object file
#

src/signal/gosignalhelper.o: /home/christian/pgm/golib/src/signal/gosignalhelper.cpp
	@echo "Building object file src/signal/gosignalhelper.o..."
	c++ -o src/signal/gosignalhelper.o -DGo_EXPORTS    -fPIC $(INCLUDE_FLAGS)  -c /home/christian/pgm/golib/src/signal/gosignalhelper.cpp

#---------------------------------------------------------
# object file
#

src/signal/gohistogram.o: /home/christian/pgm/golib/src/signal/gohistogram.cpp
	@echo "Building object file src/signal/gohistogram.o..."
	c++ -o src/signal/gohistogram.o -DGo_EXPORTS    -fPIC $(INCLUDE_FLAGS)  -c /home/christian/pgm/golib/src/signal/gohistogram.cpp

#---------------------------------------------------------
# object file
#

src/signal/gosignal3diterator.o: /home/christian/pgm/golib/src/signal/gosignal3diterator.cpp
	@echo "Building object file src/signal/gosignal3diterator.o..."
	c++ -o src/signal/gosignal3diterator.o -DGo_EXPORTS    -fPIC $(INCLUDE_FLAGS)  -c /home/christian/pgm/golib/src/signal/gosignal3diterator.cpp

#---------------------------------------------------------
# object file
#

src/signal/gosignal3dgenericiterator.o: /home/christian/pgm/golib/src/signal/gosignal3dgenericiterator.cpp
	@echo "Building object file src/signal/gosignal3dgenericiterator.o..."
	c++ -o src/signal/gosignal3dgenericiterator.o -DGo_EXPORTS    -fPIC $(INCLUDE_FLAGS)  -c /home/christian/pgm/golib/src/signal/gosignal3dgenericiterator.cpp

#---------------------------------------------------------
# object file
#

src/system/godirectory.o: /home/christian/pgm/golib/src/system/godirectory.cc
	@echo "Building object file src/system/godirectory.o..."
	c++ -o src/system/godirectory.o -DGo_EXPORTS    -fPIC $(INCLUDE_FLAGS)  -c /home/christian/pgm/golib/src/system/godirectory.cc

#---------------------------------------------------------
# object file
#

src/system/goprocess.o: /home/christian/pgm/golib/src/system/goprocess.cc
	@echo "Building object file src/system/goprocess.o..."
	c++ -o src/system/goprocess.o -DGo_EXPORTS    -fPIC $(INCLUDE_FLAGS)  -c /home/christian/pgm/golib/src/system/goprocess.cc

#---------------------------------------------------------
# object file
#

src/thread/gothread.o: /home/christian/pgm/golib/src/thread/gothread.cc
	@echo "Building object file src/thread/gothread.o..."
	c++ -o src/thread/gothread.o -DGo_EXPORTS    -fPIC $(INCLUDE_FLAGS)  -c /home/christian/pgm/golib/src/thread/gothread.cc

#---------------------------------------------------------
# object file
#

src/thread/goconsumer.o: /home/christian/pgm/golib/src/thread/goconsumer.cc
	@echo "Building object file src/thread/goconsumer.o..."
	c++ -o src/thread/goconsumer.o -DGo_EXPORTS    -fPIC $(INCLUDE_FLAGS)  -c /home/christian/pgm/golib/src/thread/goconsumer.cc

#---------------------------------------------------------
# object file
#

src/thread/goproducer.o: /home/christian/pgm/golib/src/thread/goproducer.cc
	@echo "Building object file src/thread/goproducer.o..."
	c++ -o src/thread/goproducer.o -DGo_EXPORTS    -fPIC $(INCLUDE_FLAGS)  -c /home/christian/pgm/golib/src/thread/goproducer.cc

#---------------------------------------------------------
# object file
#

src/thread/gosynchronized.o: /home/christian/pgm/golib/src/thread/gosynchronized.cc
	@echo "Building object file src/thread/gosynchronized.o..."
	c++ -o src/thread/gosynchronized.o -DGo_EXPORTS    -fPIC $(INCLUDE_FLAGS)  -c /home/christian/pgm/golib/src/thread/gosynchronized.cc

#---------------------------------------------------------
# object file
#

src/thread/gothreadobject.o: /home/christian/pgm/golib/src/thread/gothreadobject.cc
	@echo "Building object file src/thread/gothreadobject.o..."
	c++ -o src/thread/gothreadobject.o -DGo_EXPORTS    -fPIC $(INCLUDE_FLAGS)  -c /home/christian/pgm/golib/src/thread/gothreadobject.cc

#---------------------------------------------------------
# object file
#

src/types/gotype.o: /home/christian/pgm/golib/src/types/gotype.cpp
	@echo "Building object file src/types/gotype.o..."
	c++ -o src/types/gotype.o -DGo_EXPORTS    -fPIC $(INCLUDE_FLAGS)  -c /home/christian/pgm/golib/src/types/gotype.cpp

#---------------------------------------------------------
# installation
#

install: 
	@echo "Building installation install..."
	$(CMAKE_COMMAND) -P cmake_install.cmake

include cmake.depends
