#ifndef GODEFS_H
#define GODEFS_H

enum {
  GO_DIRECTION,
  GO_DIRECTION_X,
  GO_DIRECTION_Y,
  GO_DIRECTION_Z,
  GO_DIRECTION_X_NEGATIVE,
  GO_DIRECTION_Y_NEGATIVE,
  GO_DIRECTION_Z_NEGATIVE,

  GO_ID_3DCODER,
  GO_ID_3DCODERFELICS,
  GO_ID_3DCODERSUBBAND,
  GO_ID_3DCODERGOLOMB
};

#endif
